version: "3"
services:
  aws-cli-container:
    build: .
    container_name: awscli-container
    volumes:
      - ./workdir:/workdir
    working_dir: /workdir
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json